/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './timesheet-data.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './timesheet.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../content-pages.css.shim';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/control_container';
var renderType_TimesheetDataComponent_Host:import0.RenderComponentType = (null as any);
class _View_TimesheetDataComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TimesheetDataComponent_0_4:import3.TimesheetDataComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetDataComponent_Host0,renderType_TimesheetDataComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('div',rootSelector,(null as any));
    this.renderer.setElementAttribute(this._el_0,'wc-timesheet-data','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TimesheetDataComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TimesheetDataComponent_0_4 = new import3.TimesheetDataComponent(this.parentInjector.get(import8.TimesheetService));
    this._appEl_0.initComponent(this._TimesheetDataComponent_0_4,[],compView_0);
    compView_0.create(this._TimesheetDataComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TimesheetDataComponent) && (0 === requestNodeIndex))) { return this._TimesheetDataComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_TimesheetDataComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TimesheetDataComponent_Host === (null as any))) { (renderType_TimesheetDataComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_TimesheetDataComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TimesheetDataComponentNgFactory:import10.ComponentFactory<import3.TimesheetDataComponent> = new import10.ComponentFactory<import3.TimesheetDataComponent>('[wc-timesheet-data]',viewFactory_TimesheetDataComponent_Host0,import3.TimesheetDataComponent);
const styles_TimesheetDataComponent:any[] = [import11.styles];
var renderType_TimesheetDataComponent:import0.RenderComponentType = (null as any);
class _View_TimesheetDataComponent0 extends import1.AppView<import3.TimesheetDataComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _el_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _NgForm_23_3:import12.NgForm;
  _ControlContainer_23_4:any;
  _NgControlStatusGroup_23_5:import13.NgControlStatusGroup;
  _text_24:any;
  _el_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetDataComponent0,renderType_TimesheetDataComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_13 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_19 = this.renderer.createElement(parentRenderNode,'td',(null as any));
    this._el_20 = this.renderer.createElement(this._el_19,'a',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','ts-btn btn btn-warning');
    this._el_21 = this.renderer.createElement(this._el_20,'i',(null as any));
    this.renderer.setElementAttribute(this._el_21,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_21,'class','fa fa-pencil-square-o');
    this._text_22 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_19,'form',(null as any));
    this.renderer.setElementAttribute(this._el_23,'id','delete-btn');
    this.renderer.setElementAttribute(this._el_23,'onsubmit','return confirm(\'Do you really want to delete the entry?\\nIt will be lost forever!...unless you refresh\')');
    this._NgForm_23_3 = new import12.NgForm((null as any),(null as any));
    this._ControlContainer_23_4 = this._NgForm_23_3;
    this._NgControlStatusGroup_23_5 = new import13.NgControlStatusGroup(this._ControlContainer_23_4);
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'button',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','ts-btn btn btn-danger');
    this._el_26 = this.renderer.createElement(this._el_25,'i',(null as any));
    this.renderer.setElementAttribute(this._el_26,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_26,'class','fa fa-remove');
    this._text_27 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._text_28 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_23,'ngSubmit',this.eventHandler(this._handle_ngSubmit_23_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_23,'submit',this.eventHandler(this._handle_submit_23_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_23,'reset',this.eventHandler(this._handle_reset_23_2.bind(this)));
    const subscription_0:any = this._NgForm_23_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_23_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._el_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._el_26,
      this._text_27,
      this._text_28
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.NgForm) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgForm_23_3; }
    if (((token === import14.ControlContainer) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ControlContainer_23_4; }
    if (((token === import13.NgControlStatusGroup) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._NgControlStatusGroup_23_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.entry.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_2,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.entry.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_5,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.entry.date,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_8,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.entry.startTime,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_11,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'',this.context.entry.endTime,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_14,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'$',this.context.entry.dailyWage,'');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_17,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_10:any = this._NgControlStatusGroup_23_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'ng-untouched',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_23_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_23,'ng-touched',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_23_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_23,'ng-pristine',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_23_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_23,'ng-dirty',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatusGroup_23_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_23,'ng-valid',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatusGroup_23_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_23,'ng-invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onEdit()) !== false);
    return (true && pd_0);
  }
  private _handle_ngSubmit_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onDelete()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_23_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_23_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_23_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_23_3.onReset()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TimesheetDataComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TimesheetDataComponent> {
  if ((renderType_TimesheetDataComponent === (null as any))) { (renderType_TimesheetDataComponent = viewUtils.createRenderComponentType('C:/Users/Maria_2/Documents/WageCalulator/wc-from-scratch/assets/app/content-pages/timesheet/timesheet-data.component.html',0,import9.ViewEncapsulation.Emulated,styles_TimesheetDataComponent,{})); }
  return new _View_TimesheetDataComponent0(viewUtils,parentInjector,declarationEl);
}