/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './timesheet.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './timesheet.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../content-pages.css.shim';
import * as import12 from '../header.component';
import * as import13 from '@angular/forms/src/directives/ng_form';
import * as import14 from '@angular/forms/src/directives/ng_control_status';
import * as import15 from './timesheet-input.component';
import * as import16 from '@angular/common/src/directives/ng_switch';
import * as import17 from '../header.component.ngfactory';
import * as import18 from './timesheet-input.component.ngfactory';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/forms/src/directives/control_container';
import * as import21 from '@angular/common/src/directives/ng_for';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from './timesheet-data.component';
import * as import24 from './timesheet-data.component.ngfactory';
import * as import25 from '../loading.component';
import * as import26 from '../loading.component.ngfactory';
var renderType_TimesheetComponent_Host:import0.RenderComponentType = (null as any);
class _View_TimesheetComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TimesheetComponent_0_4:import3.TimesheetComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetComponent_Host0,renderType_TimesheetComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('wc-timesheet',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TimesheetComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TimesheetComponent_0_4 = new import3.TimesheetComponent(this.parentInjector.get(import8.TimesheetService));
    this._appEl_0.initComponent(this._TimesheetComponent_0_4,[],compView_0);
    compView_0.create(this._TimesheetComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TimesheetComponent) && (0 === requestNodeIndex))) { return this._TimesheetComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TimesheetComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TimesheetComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TimesheetComponent_Host === (null as any))) { (renderType_TimesheetComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_TimesheetComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TimesheetComponentNgFactory:import10.ComponentFactory<import3.TimesheetComponent> = new import10.ComponentFactory<import3.TimesheetComponent>('wc-timesheet',viewFactory_TimesheetComponent_Host0,import3.TimesheetComponent);
const styles_TimesheetComponent:any[] = [import11.styles];
var renderType_TimesheetComponent:import0.RenderComponentType = (null as any);
class _View_TimesheetComponent0 extends import1.AppView<import3.TimesheetComponent> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeaderComponent_0_4:import12.HeaderComponent;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import13.NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import14.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TimesheetInputComponent_31_4:import15.TimesheetInputComponent;
  _text_32:any;
  _el_33:any;
  _NgSwitch_33_3:import16.NgSwitch;
  _text_34:any;
  _anchor_35:any;
  /*private*/ _appEl_35:import2.AppElement;
  _TemplateRef_35_5:any;
  _NgSwitchCase_35_6:import16.NgSwitchCase;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgSwitchCase_37_6:import16.NgSwitchCase;
  _text_38:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetComponent0,renderType_TimesheetComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'wc-header',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import17.viewFactory_HeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeaderComponent_0_4 = new import12.HeaderComponent();
    this._appEl_0.initComponent(this._HeaderComponent_0_4,[],compView_0);
    compView_0.create(this._HeaderComponent_0_4,[],(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'hr',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = this.renderer.createElement(parentRenderNode,'p',(null as any));
    this._el_5 = this.renderer.createElement(this._el_4,'br',(null as any));
    this._text_6 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_7 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this.renderer.setElementAttribute(this._el_7,'id','refresh-btn');
    this._NgForm_7_3 = new import13.NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3;
    this._NgControlStatusGroup_7_5 = new import14.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'button',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','btn btn-info');
    this.renderer.setElementAttribute(this._el_9,'type','submit');
    this._text_10 = this.renderer.createText(this._el_9,'Refresh! ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'i',(null as any));
    this.renderer.setElementAttribute(this._el_11,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_11,'class','fa fa-refresh');
    this._text_12 = this.renderer.createText(this._el_7,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'p',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'h2',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Time Sheet of Employees',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_19 = this.renderer.createElement(parentRenderNode,'p',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','p-wc');
    this._text_20 = this.renderer.createText(this._el_19,'Here is your rendered csv file. You can add further entries for ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'strong',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'this',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,' month by hitting the add button below and filling in the form.',(null as any));
    this._el_24 = this.renderer.createElement(this._el_19,'br',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,' You can also refresh by clicking the refresh button i.e. all data is removed and added back straight from the\n    csv file.',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_27 = this.renderer.createElement(parentRenderNode,'a',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','btn btn-danger');
    this.renderer.setElementAttribute(this._el_27,'id','toggle-form-btn');
    this._el_28 = this.renderer.createElement(this._el_27,'i',(null as any));
    this.renderer.setElementAttribute(this._el_28,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_28,'class','fa fa-plus');
    this._text_29 = this.renderer.createText(this._el_27,'\n Add New Entry',(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_31 = this.renderer.createElement(parentRenderNode,'wc-timesheet-input',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','ts-input');
    this.renderer.setElementAttribute(this._el_31,'style','display:none;');
    this._appEl_31 = new import2.AppElement(31,(null as any),this,this._el_31);
    var compView_31:any = import18.viewFactory_TimesheetInputComponent0(this.viewUtils,this.injector(31),this._appEl_31);
    this._TimesheetInputComponent_31_4 = new import15.TimesheetInputComponent(this.parentInjector.get(import8.TimesheetService));
    this._appEl_31.initComponent(this._TimesheetInputComponent_31_4,[],compView_31);
    compView_31.create(this._TimesheetInputComponent_31_4,[],(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_33 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._NgSwitch_33_3 = new import16.NgSwitch();
    this._text_34 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._anchor_35 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_35 = new import2.AppElement(35,33,this,this._anchor_35);
    this._TemplateRef_35_5 = new import19.TemplateRef_(this._appEl_35,viewFactory_TimesheetComponent1);
    this._NgSwitchCase_35_6 = new import16.NgSwitchCase(this._appEl_35.vcRef,this._TemplateRef_35_5,this._NgSwitch_33_3);
    this._text_36 = this.renderer.createText(this._el_33,'\n  ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_33,(null as any));
    this._appEl_37 = new import2.AppElement(37,33,this,this._anchor_37);
    this._TemplateRef_37_5 = new import19.TemplateRef_(this._appEl_37,viewFactory_TimesheetComponent3);
    this._NgSwitchCase_37_6 = new import16.NgSwitchCase(this._appEl_37.vcRef,this._TemplateRef_37_5,this._NgSwitch_33_3);
    this._text_38 = this.renderer.createText(this._el_33,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_7,'ngSubmit',this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_2.bind(this)));
    const subscription_0:any = this._NgForm_7_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._anchor_35,
      this._text_36,
      this._anchor_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.HeaderComponent) && (0 === requestNodeIndex))) { return this._HeaderComponent_0_4; }
    if (((token === import13.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgForm_7_3; }
    if (((token === import20.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ControlContainer_7_4; }
    if (((token === import14.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatusGroup_7_5; }
    if (((token === import15.TimesheetInputComponent) && (31 === requestNodeIndex))) { return this._TimesheetInputComponent_31_4; }
    if (((token === import19.TemplateRef) && (35 === requestNodeIndex))) { return this._TemplateRef_35_5; }
    if (((token === import16.NgSwitchCase) && (35 === requestNodeIndex))) { return this._NgSwitchCase_35_6; }
    if (((token === import19.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import16.NgSwitchCase) && (37 === requestNodeIndex))) { return this._NgSwitchCase_37_6; }
    if (((token === import16.NgSwitch) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgSwitch_33_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TimesheetInputComponent_31_4.ngOnInit(); }
    const currVal_10:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgSwitch_33_3.ngSwitch = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = false;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgSwitchCase_35_6.ngSwitchCase = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = true;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgSwitchCase_37_6.ngSwitchCase = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_ngSubmit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onRefresh()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.toggleForm()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TimesheetComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TimesheetComponent> {
  if ((renderType_TimesheetComponent === (null as any))) { (renderType_TimesheetComponent = viewUtils.createRenderComponentType('C:/Users/Maria_2/Documents/WageCalulator/wc-from-scratch/assets/app/content-pages/timesheet/timesheet.component.html',0,import9.ViewEncapsulation.Emulated,styles_TimesheetComponent,{})); }
  return new _View_TimesheetComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_TimesheetComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _anchor_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _TemplateRef_31_5:any;
  _NgFor_31_6:import21.NgFor;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetComponent1,renderType_TimesheetComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','table-responsive');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'table',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'tbody',(null as any));
    this._el_7 = this.renderer.createElement(this._el_6,'tr',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Name',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Id',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Date',(null as any));
    this._text_17 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Start Time',(null as any));
    this._text_20 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'End Time',(null as any));
    this._text_23 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_7,'th',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'Daily Wage',(null as any));
    this._text_26 = this.renderer.createText(this._el_7,'\n              ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_7,'th',(null as any));
    this.renderer.setElementAttribute(this._el_27,'id','th-edit-delete');
    this._text_28 = this.renderer.createText(this._el_27,'Edit/Delete',(null as any));
    this._text_29 = this.renderer.createText(this._el_7,'\n          ',(null as any));
    this._text_30 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._anchor_31 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_31 = new import2.AppElement(31,6,this,this._anchor_31);
    this._TemplateRef_31_5 = new import19.TemplateRef_(this._appEl_31,viewFactory_TimesheetComponent2);
    this._NgFor_31_6 = new import21.NgFor(this._appEl_31.vcRef,this._TemplateRef_31_5,this.parent.parentInjector.get(import22.IterableDiffers),this.parent.ref);
    this._text_32 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_34 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._anchor_31,
      this._text_32,
      this._text_33,
      this._text_34
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (31 === requestNodeIndex))) { return this._TemplateRef_31_5; }
    if (((token === import21.NgFor) && (31 === requestNodeIndex))) { return this._NgFor_31_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.entries;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_31_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_31_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_31_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TimesheetComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TimesheetComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_TimesheetComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TimesheetDataComponent_0_4:import23.TimesheetDataComponent;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetComponent2,renderType_TimesheetComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'tr',(null as any));
    this.renderer.setElementAttribute(this._el_0,'wc-timesheet-data','');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import24.viewFactory_TimesheetDataComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TimesheetDataComponent_0_4 = new import23.TimesheetDataComponent(this.parent.parent.parentInjector.get(import8.TimesheetService));
    this._appEl_0.initComponent(this._TimesheetDataComponent_0_4,[],compView_0);
    compView_0.create(this._TimesheetDataComponent_0_4,[],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.TimesheetDataComponent) && (0 === requestNodeIndex))) { return this._TimesheetDataComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._TimesheetDataComponent_0_4.entry = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TimesheetComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TimesheetComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_TimesheetComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _LoadingIndicator_9_4:import25.LoadingIndicator;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetComponent3,renderType_TimesheetComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'table',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','loader-container');
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h2',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Getting timesheet entries...',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'loading-indicator',(null as any));
    this._appEl_9 = new import2.AppElement(9,4,this,this._el_9);
    var compView_9:any = import26.viewFactory_LoadingIndicator0(this.viewUtils,this.injector(9),this._appEl_9);
    this._LoadingIndicator_9_4 = new import25.LoadingIndicator();
    this._appEl_9.initComponent(this._LoadingIndicator_9_4,[],compView_9);
    compView_9.create(this._LoadingIndicator_9_4,[],(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.LoadingIndicator) && (9 === requestNodeIndex))) { return this._LoadingIndicator_9_4; }
    return notFoundResult;
  }
}
function viewFactory_TimesheetComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_TimesheetComponent3(viewUtils,parentInjector,declarationEl);
}