/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './timesheet-input.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './timesheet.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../content-pages.css.shim';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/ng_model';
import * as import16 from '@angular/forms/src/directives/validators';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/forms/src/directives/control_value_accessor';
import * as import19 from '@angular/forms/src/directives/ng_control';
import * as import20 from '@angular/forms/src/validators';
import * as import21 from '@angular/forms/src/directives/control_container';
var renderType_TimesheetInputComponent_Host:import0.RenderComponentType = (null as any);
class _View_TimesheetInputComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TimesheetInputComponent_0_4:import3.TimesheetInputComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetInputComponent_Host0,renderType_TimesheetInputComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('wc-timesheet-input',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TimesheetInputComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TimesheetInputComponent_0_4 = new import3.TimesheetInputComponent(this.parentInjector.get(import8.TimesheetService));
    this._appEl_0.initComponent(this._TimesheetInputComponent_0_4,[],compView_0);
    compView_0.create(this._TimesheetInputComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TimesheetInputComponent) && (0 === requestNodeIndex))) { return this._TimesheetInputComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TimesheetInputComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TimesheetInputComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TimesheetInputComponent_Host === (null as any))) { (renderType_TimesheetInputComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_TimesheetInputComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TimesheetInputComponentNgFactory:import10.ComponentFactory<import3.TimesheetInputComponent> = new import10.ComponentFactory<import3.TimesheetInputComponent>('wc-timesheet-input',viewFactory_TimesheetInputComponent_Host0,import3.TimesheetInputComponent);
const styles_TimesheetInputComponent:any[] = [import11.styles];
var renderType_TimesheetInputComponent:import0.RenderComponentType = (null as any);
class _View_TimesheetInputComponent0 extends import1.AppView<import3.TimesheetInputComponent> {
  _el_0:any;
  _NgForm_0_3:import12.NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import13.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _DefaultValueAccessor_2_3:import14.DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_2_4:any[];
  _NgModel_2_5:import15.NgModel;
  _NgControl_2_6:any;
  _NgControlStatus_2_7:import13.NgControlStatus;
  _text_3:any;
  _el_4:any;
  _DefaultValueAccessor_4_3:import14.DefaultValueAccessor;
  _RequiredValidator_4_4:import16.RequiredValidator;
  _NG_VALIDATORS_4_5:any[];
  _NG_VALUE_ACCESSOR_4_6:any[];
  _NgModel_4_7:import15.NgModel;
  _NgControl_4_8:any;
  _NgControlStatus_4_9:import13.NgControlStatus;
  _text_5:any;
  _el_6:any;
  _DefaultValueAccessor_6_3:import14.DefaultValueAccessor;
  _PatternValidator_6_4:import16.PatternValidator;
  _NG_VALIDATORS_6_5:any[];
  _NG_VALUE_ACCESSOR_6_6:any[];
  _NgModel_6_7:import15.NgModel;
  _NgControl_6_8:any;
  _NgControlStatus_6_9:import13.NgControlStatus;
  _text_7:any;
  _el_8:any;
  _DefaultValueAccessor_8_3:import14.DefaultValueAccessor;
  _RequiredValidator_8_4:import16.RequiredValidator;
  _PatternValidator_8_5:import16.PatternValidator;
  _NG_VALIDATORS_8_6:any[];
  _NG_VALUE_ACCESSOR_8_7:any[];
  _NgModel_8_8:import15.NgModel;
  _NgControl_8_9:any;
  _NgControlStatus_8_10:import13.NgControlStatus;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import14.DefaultValueAccessor;
  _RequiredValidator_10_4:import16.RequiredValidator;
  _PatternValidator_10_5:import16.PatternValidator;
  _NG_VALIDATORS_10_6:any[];
  _NG_VALUE_ACCESSOR_10_7:any[];
  _NgModel_10_8:import15.NgModel;
  _NgControl_10_9:any;
  _NgControlStatus_10_10:import13.NgControlStatus;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_59:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TimesheetInputComponent0,renderType_TimesheetInputComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'form',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','form');
    this._NgForm_0_3 = new import12.NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3;
    this._NgControlStatusGroup_0_5 = new import13.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_2,'name','name');
    this.renderer.setElementAttribute(this._el_2,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_2,'type','text');
    this._DefaultValueAccessor_2_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_2));
    this._NG_VALUE_ACCESSOR_2_4 = [this._DefaultValueAccessor_2_3];
    this._NgModel_2_5 = new import15.NgModel(this._ControlContainer_0_4,(null as any),(null as any),this._NG_VALUE_ACCESSOR_2_4);
    this._NgControl_2_6 = this._NgModel_2_5;
    this._NgControlStatus_2_7 = new import13.NgControlStatus(this._NgControl_2_6);
    this._text_3 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_4,'name','id');
    this.renderer.setElementAttribute(this._el_4,'placeholder','ID');
    this.renderer.setElementAttribute(this._el_4,'required','');
    this.renderer.setElementAttribute(this._el_4,'type','text');
    this._DefaultValueAccessor_4_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_4));
    this._RequiredValidator_4_4 = new import16.RequiredValidator();
    this._NG_VALIDATORS_4_5 = [this._RequiredValidator_4_4];
    this._NG_VALUE_ACCESSOR_4_6 = [this._DefaultValueAccessor_4_3];
    this._NgModel_4_7 = new import15.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_4_5,(null as any),this._NG_VALUE_ACCESSOR_4_6);
    this._NgControl_4_8 = this._NgModel_4_7;
    this._NgControlStatus_4_9 = new import13.NgControlStatus(this._NgControl_4_8);
    this._text_5 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','datepicker');
    this.renderer.setElementAttribute(this._el_6,'name','date');
    this.renderer.setElementAttribute(this._el_6,'pattern','([1-9]|0[1-9]|1[0-9]|2[0-9]|3[01]).(3|03).2014');
    this.renderer.setElementAttribute(this._el_6,'placeholder','Date eg. 23.3.2014');
    this.renderer.setElementAttribute(this._el_6,'title','For this month i.e. 3/2014 in form dd.mm.yyyy');
    this.renderer.setElementAttribute(this._el_6,'type','text');
    this._DefaultValueAccessor_6_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_6));
    this._PatternValidator_6_4 = new import16.PatternValidator();
    this._NG_VALIDATORS_6_5 = [this._PatternValidator_6_4];
    this._NG_VALUE_ACCESSOR_6_6 = [this._DefaultValueAccessor_6_3];
    this._NgModel_6_7 = new import15.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_6_5,(null as any),this._NG_VALUE_ACCESSOR_6_6);
    this._NgControl_6_8 = this._NgModel_6_7;
    this._NgControlStatus_6_9 = new import13.NgControlStatus(this._NgControl_6_8);
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_8,'name','startTime');
    this.renderer.setElementAttribute(this._el_8,'pattern','([01]?[0-9]|2[0-3]):(00|15|30|45)');
    this.renderer.setElementAttribute(this._el_8,'placeholder','Start Time eg. 14:00');
    this.renderer.setElementAttribute(this._el_8,'required','');
    this.renderer.setElementAttribute(this._el_8,'title','24h format. hh:mm. Rounded to nearest 15 min.');
    this.renderer.setElementAttribute(this._el_8,'type','text');
    this._DefaultValueAccessor_8_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_8));
    this._RequiredValidator_8_4 = new import16.RequiredValidator();
    this._PatternValidator_8_5 = new import16.PatternValidator();
    this._NG_VALIDATORS_8_6 = [
      this._RequiredValidator_8_4,
      this._PatternValidator_8_5
    ]
    ;
    this._NG_VALUE_ACCESSOR_8_7 = [this._DefaultValueAccessor_8_3];
    this._NgModel_8_8 = new import15.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_8_6,(null as any),this._NG_VALUE_ACCESSOR_8_7);
    this._NgControl_8_9 = this._NgModel_8_8;
    this._NgControlStatus_8_10 = new import13.NgControlStatus(this._NgControl_8_9);
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'name','endTime');
    this.renderer.setElementAttribute(this._el_10,'pattern','([01]?[0-9]|2[0-3]):(00|15|30|45)');
    this.renderer.setElementAttribute(this._el_10,'placeholder','End Time eg. 3:00');
    this.renderer.setElementAttribute(this._el_10,'required','');
    this.renderer.setElementAttribute(this._el_10,'title','24h format. hh:mm. Rounded to nearest 15 min.');
    this.renderer.setElementAttribute(this._el_10,'type','text');
    this._DefaultValueAccessor_10_3 = new import14.DefaultValueAccessor(this.renderer,new import17.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import16.RequiredValidator();
    this._PatternValidator_10_5 = new import16.PatternValidator();
    this._NG_VALIDATORS_10_6 = [
      this._RequiredValidator_10_4,
      this._PatternValidator_10_5
    ]
    ;
    this._NG_VALUE_ACCESSOR_10_7 = [this._DefaultValueAccessor_10_3];
    this._NgModel_10_8 = new import15.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_10_6,(null as any),this._NG_VALUE_ACCESSOR_10_7);
    this._NgControl_10_9 = this._NgModel_10_8;
    this._NgControlStatus_10_10 = new import13.NgControlStatus(this._NgControl_10_9);
    this._text_11 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn btn-success');
    this.renderer.setElementAttribute(this._el_12,'type','submit');
    this._text_13 = this.renderer.createText(this._el_12,'Save',(null as any));
    this._text_14 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','btn btn-danger');
    this.renderer.setElementAttribute(this._el_15,'type','submit');
    this._el_16 = this.renderer.createElement(this._el_15,'i',(null as any));
    this.renderer.setElementAttribute(this._el_16,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_16,'class','fa fa-ban');
    this._text_17 = this.renderer.createText(this._el_15,' Cancel\n',(null as any));
    this._text_18 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    const subscription_0:any = this._NgForm_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_2,'input',this.eventHandler(this._handle_input_2_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_2,'blur',this.eventHandler(this._handle_blur_2_1.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_4,'input',this.eventHandler(this._handle_input_4_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_4,'blur',this.eventHandler(this._handle_blur_4_1.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_6,'input',this.eventHandler(this._handle_input_6_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_6,'blur',this.eventHandler(this._handle_blur_6_1.bind(this)));
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_8,'input',this.eventHandler(this._handle_input_8_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_8,'blur',this.eventHandler(this._handle_blur_8_1.bind(this)));
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    var disposable_11:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_0.bind(this)));
    var disposable_12:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_1.bind(this)));
    this._expr_59 = import7.UNINITIALIZED;
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    var disposable_13:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (2 === requestNodeIndex))) { return this._DefaultValueAccessor_2_3; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (2 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_2_4; }
    if (((token === import15.NgModel) && (2 === requestNodeIndex))) { return this._NgModel_2_5; }
    if (((token === import19.NgControl) && (2 === requestNodeIndex))) { return this._NgControl_2_6; }
    if (((token === import13.NgControlStatus) && (2 === requestNodeIndex))) { return this._NgControlStatus_2_7; }
    if (((token === import14.DefaultValueAccessor) && (4 === requestNodeIndex))) { return this._DefaultValueAccessor_4_3; }
    if (((token === import16.RequiredValidator) && (4 === requestNodeIndex))) { return this._RequiredValidator_4_4; }
    if (((token === import20.NG_VALIDATORS) && (4 === requestNodeIndex))) { return this._NG_VALIDATORS_4_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (4 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_4_6; }
    if (((token === import15.NgModel) && (4 === requestNodeIndex))) { return this._NgModel_4_7; }
    if (((token === import19.NgControl) && (4 === requestNodeIndex))) { return this._NgControl_4_8; }
    if (((token === import13.NgControlStatus) && (4 === requestNodeIndex))) { return this._NgControlStatus_4_9; }
    if (((token === import14.DefaultValueAccessor) && (6 === requestNodeIndex))) { return this._DefaultValueAccessor_6_3; }
    if (((token === import16.PatternValidator) && (6 === requestNodeIndex))) { return this._PatternValidator_6_4; }
    if (((token === import20.NG_VALIDATORS) && (6 === requestNodeIndex))) { return this._NG_VALIDATORS_6_5; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (6 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_6_6; }
    if (((token === import15.NgModel) && (6 === requestNodeIndex))) { return this._NgModel_6_7; }
    if (((token === import19.NgControl) && (6 === requestNodeIndex))) { return this._NgControl_6_8; }
    if (((token === import13.NgControlStatus) && (6 === requestNodeIndex))) { return this._NgControlStatus_6_9; }
    if (((token === import14.DefaultValueAccessor) && (8 === requestNodeIndex))) { return this._DefaultValueAccessor_8_3; }
    if (((token === import16.RequiredValidator) && (8 === requestNodeIndex))) { return this._RequiredValidator_8_4; }
    if (((token === import16.PatternValidator) && (8 === requestNodeIndex))) { return this._PatternValidator_8_5; }
    if (((token === import20.NG_VALIDATORS) && (8 === requestNodeIndex))) { return this._NG_VALIDATORS_8_6; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (8 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_8_7; }
    if (((token === import15.NgModel) && (8 === requestNodeIndex))) { return this._NgModel_8_8; }
    if (((token === import19.NgControl) && (8 === requestNodeIndex))) { return this._NgControl_8_9; }
    if (((token === import13.NgControlStatus) && (8 === requestNodeIndex))) { return this._NgControlStatus_8_10; }
    if (((token === import14.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3; }
    if (((token === import16.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4; }
    if (((token === import16.PatternValidator) && (10 === requestNodeIndex))) { return this._PatternValidator_10_5; }
    if (((token === import20.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_6; }
    if (((token === import18.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_7; }
    if (((token === import15.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_8; }
    if (((token === import19.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_9; }
    if (((token === import13.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_10; }
    if (((token === import12.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgForm_0_3; }
    if (((token === import21.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._ControlContainer_0_4; }
    if (((token === import13.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_11:any = 'name';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgModel_2_5.name = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = ((this.context.entry == (null as any))? (null as any): this.context.entry.name);
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgModel_2_5.model = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._NgModel_2_5.ngOnChanges(changes); }
    const currVal_21:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._RequiredValidator_4_4.required = currVal_21;
      this._expr_21 = currVal_21;
    }
    changes = (null as any);
    const currVal_23:any = 'id';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._NgModel_4_7.name = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = ((this.context.entry == (null as any))? (null as any): this.context.entry.id);
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._NgModel_4_7.model = currVal_24;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_24,currVal_24);
      this._expr_24 = currVal_24;
    }
    if ((changes !== (null as any))) { this._NgModel_4_7.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_33:any = '([1-9]|0[1-9]|1[0-9]|2[0-9]|3[01]).(3|03).2014';
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._PatternValidator_6_4.pattern = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['pattern'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._PatternValidator_6_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_35:any = 'date';
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this._NgModel_6_7.name = currVal_35;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_35,currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = ((this.context.entry == (null as any))? (null as any): this.context.entry.date);
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._NgModel_6_7.model = currVal_36;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_36,currVal_36);
      this._expr_36 = currVal_36;
    }
    if ((changes !== (null as any))) { this._NgModel_6_7.ngOnChanges(changes); }
    const currVal_45:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this._RequiredValidator_8_4.required = currVal_45;
      this._expr_45 = currVal_45;
    }
    changes = (null as any);
    const currVal_47:any = '([01]?[0-9]|2[0-3]):(00|15|30|45)';
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this._PatternValidator_8_5.pattern = currVal_47;
      if ((changes === (null as any))) { (changes = {}); }
      changes['pattern'] = new import7.SimpleChange(this._expr_47,currVal_47);
      this._expr_47 = currVal_47;
    }
    if ((changes !== (null as any))) { this._PatternValidator_8_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_49:any = 'startTime';
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this._NgModel_8_8.name = currVal_49;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_49,currVal_49);
      this._expr_49 = currVal_49;
    }
    const currVal_50:any = ((this.context.entry == (null as any))? (null as any): this.context.entry.startTime);
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._NgModel_8_8.model = currVal_50;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_50,currVal_50);
      this._expr_50 = currVal_50;
    }
    if ((changes !== (null as any))) { this._NgModel_8_8.ngOnChanges(changes); }
    const currVal_59:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_59,currVal_59)) {
      this._RequiredValidator_10_4.required = currVal_59;
      this._expr_59 = currVal_59;
    }
    changes = (null as any);
    const currVal_61:any = '([01]?[0-9]|2[0-3]):(00|15|30|45)';
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this._PatternValidator_10_5.pattern = currVal_61;
      if ((changes === (null as any))) { (changes = {}); }
      changes['pattern'] = new import7.SimpleChange(this._expr_61,currVal_61);
      this._expr_61 = currVal_61;
    }
    if ((changes !== (null as any))) { this._PatternValidator_10_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_63:any = 'endTime';
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this._NgModel_10_8.name = currVal_63;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_63,currVal_63);
      this._expr_63 = currVal_63;
    }
    const currVal_64:any = ((this.context.entry == (null as any))? (null as any): this.context.entry.endTime);
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this._NgModel_10_8.model = currVal_64;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_64,currVal_64);
      this._expr_64 = currVal_64;
    }
    if ((changes !== (null as any))) { this._NgModel_10_8.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = this._NgControlStatus_2_7.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this._NgControlStatus_2_7.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_2_7.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_2_7.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_2_7.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_2_7.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = (this._RequiredValidator_4_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementAttribute(this._el_4,'required',((currVal_22 == (null as any))? (null as any): currVal_22.toString()));
      this._expr_22 = currVal_22;
    }
    const currVal_25:any = this._NgControlStatus_4_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_4,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_4_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_4,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_4_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_4,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_4_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_4,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_4_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_4,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_4_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_4,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_34:any = (this._PatternValidator_6_4.pattern? this._PatternValidator_6_4.pattern: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementAttribute(this._el_6,'pattern',((currVal_34 == (null as any))? (null as any): currVal_34.toString()));
      this._expr_34 = currVal_34;
    }
    const currVal_37:any = this._NgControlStatus_6_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_6,'ng-untouched',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_6_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_6,'ng-touched',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_6_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_6,'ng-pristine',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_6_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_6,'ng-dirty',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_6_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_6,'ng-valid',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_6_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_6,'ng-invalid',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_46:any = (this._RequiredValidator_8_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementAttribute(this._el_8,'required',((currVal_46 == (null as any))? (null as any): currVal_46.toString()));
      this._expr_46 = currVal_46;
    }
    const currVal_48:any = (this._PatternValidator_8_5.pattern? this._PatternValidator_8_5.pattern: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementAttribute(this._el_8,'pattern',((currVal_48 == (null as any))? (null as any): currVal_48.toString()));
      this._expr_48 = currVal_48;
    }
    const currVal_51:any = this._NgControlStatus_8_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_8,'ng-untouched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_8_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_8,'ng-touched',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_8_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_8,'ng-pristine',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_8_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_8,'ng-dirty',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_8_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_8,'ng-valid',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = this._NgControlStatus_8_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementClass(this._el_8,'ng-invalid',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_60:any = (this._RequiredValidator_10_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementAttribute(this._el_10,'required',((currVal_60 == (null as any))? (null as any): currVal_60.toString()));
      this._expr_60 = currVal_60;
    }
    const currVal_62:any = (this._PatternValidator_10_5.pattern? this._PatternValidator_10_5.pattern: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this.renderer.setElementAttribute(this._el_10,'pattern',((currVal_62 == (null as any))? (null as any): currVal_62.toString()));
      this._expr_62 = currVal_62;
    }
    const currVal_65:any = this._NgControlStatus_10_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_10_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_10_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_10_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_10_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_70:any = this._NgControlStatus_10_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_70);
      this._expr_70 = currVal_70;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_2_5.ngOnDestroy();
    this._NgModel_4_7.ngOnDestroy();
    this._NgModel_6_7.ngOnDestroy();
    this._NgModel_8_8.ngOnDestroy();
    this._NgModel_10_8.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_0_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_2_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_2_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_4_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_4_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_4_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_6_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_6_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_8_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_8_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_8_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_input_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onClear(this._NgForm_0_3)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TimesheetInputComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TimesheetInputComponent> {
  if ((renderType_TimesheetInputComponent === (null as any))) { (renderType_TimesheetInputComponent = viewUtils.createRenderComponentType('C:/Users/Maria_2/Documents/WageCalulator/wc-from-scratch/assets/app/content-pages/timesheet/timesheet-input.component.html',0,import9.ViewEncapsulation.Emulated,styles_TimesheetInputComponent,{})); }
  return new _View_TimesheetInputComponent0(viewUtils,parentInjector,declarationEl);
}