/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './loading.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_LoadingIndicator_Host:import0.RenderComponentType = (null as any);
class _View_LoadingIndicator_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _LoadingIndicator_0_4:import3.LoadingIndicator;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoadingIndicator_Host0,renderType_LoadingIndicator_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('loading-indicator',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoadingIndicator0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoadingIndicator_0_4 = new import3.LoadingIndicator();
    this._appEl_0.initComponent(this._LoadingIndicator_0_4,[],compView_0);
    compView_0.create(this._LoadingIndicator_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.LoadingIndicator) && (0 === requestNodeIndex))) { return this._LoadingIndicator_0_4; }
    return notFoundResult;
  }
}
function viewFactory_LoadingIndicator_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_LoadingIndicator_Host === (null as any))) { (renderType_LoadingIndicator_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_LoadingIndicator_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoadingIndicatorNgFactory:import9.ComponentFactory<import3.LoadingIndicator> = new import9.ComponentFactory<import3.LoadingIndicator>('loading-indicator',viewFactory_LoadingIndicator_Host0,import3.LoadingIndicator);
const styles_LoadingIndicator:any[] = [];
var renderType_LoadingIndicator:import0.RenderComponentType = (null as any);
class _View_LoadingIndicator0 extends import1.AppView<import3.LoadingIndicator> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_LoadingIndicator0,renderType_LoadingIndicator,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','loader loader-small');
    this.init([],[this._el_0],[],[]);
    return (null as any);
  }
}
export function viewFactory_LoadingIndicator0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.LoadingIndicator> {
  if ((renderType_LoadingIndicator === (null as any))) { (renderType_LoadingIndicator = viewUtils.createRenderComponentType('C:/Users/Maria_2/Documents/WageCalulator/wc-from-scratch/assets/app/content-pages/loading.component.ts class LoadingIndicator - inline template',0,import8.ViewEncapsulation.None,styles_LoadingIndicator,{})); }
  return new _View_LoadingIndicator0(viewUtils,parentInjector,declarationEl);
}