/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.view[_ngcontent-%COMP%] {\r\n    margin-left: 50px;\r\n    padding: 20px!important;\r\n    border-radius: 30px!important;\r\n}\r\n\r\n#titleBox[_ngcontent-%COMP%] {\r\n    display: flex;\r\n    width: 360px;\r\n    height: 200px;\r\n    margin: 200px auto;\r\n    border-radius: 25px;\r\n    background: #f7f7f7;\r\n    box-shadow: 0 0 3px rgba(0, 0, 0, .1);\r\n    align-items: center;\r\n    justify-content: center;\r\n}\r\n\r\n#mainTitle[_ngcontent-%COMP%] {\r\n    font-family: \'PT sans\', sans-serif!important;\r\n    font-size: 42px;\r\n    margin-bottom: 20px;\r\n    text-align: center;\r\n}'];